#!/bin/bash

set -e
export HOME=/app
hash -r
cd $HOME

case "\$(basename \$0)" in
  start)
    if [[ -f Procfile ]]; then
      # Generate supervisord.conf:
      bash /build/procfile-to-supervisord /app/Procfile /app/SCALE > supervisord.conf

      # Create /var/log/app directory
      mkdir -p /var/log/app

      # Display the generated supervisord.conf:
      echo "Generated supervisord.conf:"
      cat -n supervisord.conf

      # Start up the app:
      supervisord -c supervisord.conf
    else
      command="\$(ruby -e "require 'yaml';puts (YAML.load_file('.release')['default_process_types'] || {})['\$1']")"
    fi
    ;;
  *)
    bash /dokku-run $@
    ;;
esac
